FROM ubuntu

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
		python3.8 \
		git \
		vim

#docker build -t bonus03 .
#docker run -it --rm bonus03

#hello.py
#printt("Hello")
#python3.8 hello.py
